-- Seed auction config singleton
INSERT INTO auction_config (id) VALUES (1);

-- World Cup 2026 qualified teams (48 teams, 12 groups of 4)
-- Groups and opponents are placeholders — update once the official draw is confirmed.
INSERT INTO teams (name, flag_emoji, group_label) VALUES
  ('Argentina',        '🇦🇷', 'A'),
  ('Brazil',           '🇧🇷', 'A'),
  ('France',           '🇫🇷', 'A'),
  ('Germany',          '🇩🇪', 'A'),
  ('England',          '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'B'),
  ('Spain',            '🇪🇸', 'B'),
  ('Portugal',         '🇵🇹', 'B'),
  ('Netherlands',      '🇳🇱', 'B'),
  ('United States',    '🇺🇸', 'C'),
  ('Mexico',           '🇲🇽', 'C'),
  ('Canada',           '🇨🇦', 'C'),
  ('Morocco',          '🇲🇦', 'C'),
  ('Japan',            '🇯🇵', 'D'),
  ('South Korea',      '🇰🇷', 'D'),
  ('Australia',        '🇦🇺', 'D'),
  ('Saudi Arabia',     '🇸🇦', 'D'),
  ('Belgium',          '🇧🇪', 'E'),
  ('Italy',            '🇮🇹', 'E'),
  ('Croatia',          '🇭🇷', 'E'),
  ('Turkey',           '🇹🇷', 'E'),
  ('Colombia',         '🇨🇴', 'F'),
  ('Uruguay',          '🇺🇾', 'F'),
  ('Ecuador',          '🇪🇨', 'F'),
  ('Senegal',          '🇸🇳', 'F'),
  ('Poland',           '🇵🇱', 'G'),
  ('Serbia',           '🇷🇸', 'G'),
  ('Ukraine',          '🇺🇦', 'G'),
  ('Nigeria',          '🇳🇬', 'G'),
  ('Switzerland',      '🇨🇭', 'H'),
  ('Denmark',          '🇩🇰', 'H'),
  ('Austria',          '🇦🇹', 'H'),
  ('Egypt',            '🇪🇬', 'H'),
  ('Iran',             '🇮🇷', 'I'),
  ('Iraq',             '🇮🇶', 'I'),
  ('New Zealand',      '🇳🇿', 'I'),
  ('Ivory Coast',      '🇨🇮', 'I'),
  ('Honduras',         '🇭🇳', 'J'),
  ('Panama',           '🇵🇦', 'J'),
  ('Venezuela',        '🇻🇪', 'J'),
  ('Ghana',            '🇬🇭', 'J'),
  ('Chile',            '🇨🇱', 'K'),
  ('Peru',             '🇵🇪', 'K'),
  ('Bolivia',          '🇧🇴', 'K'),
  ('South Africa',     '🇿🇦', 'K'),
  ('Cameroon',         '🇨🇲', 'L'),
  ('Czech Republic',   '🇨🇿', 'L'),
  ('Paraguay',         '🇵🇾', 'L'),
  ('Albania',          '🇦🇱', 'L');
